# Project Information
site_name: "Bardess Project Documentation"
site_description: "Comprehensive documentation for Your Project"
site_author: "Bardess A Cleartelligence Company"
site_url: "https://bardess-group-ltd.github.io/documentation/"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

plugins:
  - search
  - awesome-pages

# Build settings (optional)
site_dir: site


extra_css:
  - css/custom.css  # Optional custom CSS