# Project Information
site_name: "Bardess Project Documentation"
site_description: "Comprehensive documentation for Your Project"
site_author: "Bardess A Cleartelligence Company"
site_url: "https://bardess-group-ltd.github.io/documentation/"

# Configuration
theme:
  name: material  # You can use the 'readthedocs' theme or another if you prefer

nav:
  - Home: index.md
  - Documentation: /docs/

# Build settings (optional)
site_dir: site
